# Generated by Django 4.2 on 2023-05-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Pincode',
            field=models.IntegerField(),
        ),
    ]
