# Generated by Django 4.2.1 on 2023-05-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_dob_alter_employee_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.CharField(max_length=100),
        ),
    ]
