# Generated by Django 4.2.1 on 2023-05-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_emppayment_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
    ]
