# Generated by Django 4.2.1 on 2023-05-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_emplogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpLogin',
        ),
    ]
